# Generated by Django 2.1.3 on 2018-12-08 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='child',
            old_name='birth_date',
            new_name='birth_day',
        ),
        migrations.RenameField(
            model_name='parent',
            old_name='birth_date',
            new_name='birth_day',
        ),
    ]
