# Generated by Django 2.1.3 on 2018-12-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20181208_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='gender',
            field=models.CharField(max_length=1),
        ),
    ]
