# Generated by Django 2.1.3 on 2018-12-08 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20181208_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
