# Generated by Django 2.1.3 on 2019-04-15 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20190415_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='current_zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='database.Danger_zone'),
        ),
    ]
