# Generated by Django 2.1.3 on 2019-05-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_auto_20190415_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
        migrations.AddField(
            model_name='parent',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
