# Generated by Django 2.1.3 on 2019-05-21 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_auto_20190521_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='current_zone',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='database.Danger_zone'),
        ),
    ]
