# Generated by Django 2.1.3 on 2019-05-22 18:26

import database.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_auto_20190521_2311'),
    ]

    operations = [

    ]
