# Generated by Django 2.1.3 on 2019-06-02 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_auto_20190522_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=300)),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Device')),
            ],
        ),
    ]
