# Generated by Django 2.1.3 on 2019-06-03 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
