# Generated by Django 2.1.3 on 2019-06-03 19:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_message_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='creation_time',
            field=models.TimeField(default=datetime.datetime(2019, 6, 3, 22, 52, 41, 27519)),
        ),
    ]
