# Generated by Django 2.1.3 on 2019-06-03 20:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_message_creation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='creation_time',
            field=models.DateField(default=datetime.datetime(2019, 6, 3, 23, 0, 32, 408582)),
        ),
    ]
