# Generated by Django 2.1.3 on 2019-06-11 19:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0021_auto_20190611_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='current_zone',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='database.Danger_zone'),
        ),
        migrations.AlterField(
            model_name='message',
            name='creation_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 11, 22, 21, 36, 501160)),
        ),
    ]
