# Generated by Django 2.1.3 on 2020-04-30 12:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0023_auto_20190611_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='device',
            name='current_zone',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='database.Danger_zone'),
        ),
        migrations.AlterField(
            model_name='message',
            name='creation_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 30, 15, 2, 1, 782410)),
        ),
    ]
