# Generated by Django 2.1.3 on 2020-05-04 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0024_auto_20200430_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='notify',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='creation_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 4, 13, 6, 58, 547935)),
        ),
    ]
