# Generated by Django 2.1.3 on 2020-05-04 10:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0025_auto_20200504_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='notify',
        ),
        migrations.AddField(
            model_name='device',
            name='mockedLocation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='creation_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 4, 13, 25, 16, 292702)),
        ),
    ]
